import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import AdminNavigationBar from '@/component/AdminNavigationBar';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function AdminLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen overflow-hidden`}
            >
                <AdminNavigationBar />
                <div className="flex-1 overflow-auto bg-gray-100">
                    {children}
                </div>
            </body>
        </html>
    );
}
