import { Geist, Geist_Mono } from 'next/font/google';
import UserNavigationBar from '@/component/UserNavigatioanBar';
import { auth } from '@/lib/auth';
import { headers } from 'next/headers';
import '../globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function UsertLayout({ children }) {
    const session = await auth.api.getSession({
        headers: await headers(),
    });

    if (!session) {
        redirect('/login');
    }

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen overflow-hidden`}
            >
                <UserNavigationBar session={session} />

                <div className="flex-1 overflow-auto bg-gray-100">
                    {children}
                </div>
            </body>
        </html>
    );
}
